# Generated by Django 3.1.3 on 2020-11-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='my_like',
        ),
    ]
